site_name: Keycloak Config Operator
site_description: Kubernetes operator for managing Keycloak configuration.
site_url: https://clouddicted.github.io/keycloak-config-operator/
repo_url: https://github.com/clouddicted/keycloak-config-operator
repo_name: clouddicted/keycloak-config-operator
edit_uri: edit/main/docs/
strict: true

theme:
  name: material
  language: en
  features:
    - content.code.copy
    - navigation.sections
    - navigation.top

nav:
  - Home: index.md
  - Compatibility: compatibility.md
  - Configuration Support: configuration-support.md
  - API Reference: api-reference.md

plugins:
  - search
  - crd-viewer
  - macros:
      modules:
        - mkdocs_crd_viewer.macros

extra:
  version:
    provider: mike
    alias: true

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
