{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "keycloak-config-operator.fullname" . }}
  labels:
    {{- include "keycloak-config-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - list
      - watch
  {{- if not .Values.watchNamespaces }}
  {{- include "keycloak-config-operator.namespacedRules" . | nindent 2 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "keycloak-config-operator.fullname" . }}
  labels:
    {{- include "keycloak-config-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "keycloak-config-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "keycloak-config-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- range $namespace := .Values.watchNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "keycloak-config-operator.fullname" $ }}
  namespace: {{ $namespace | quote }}
  labels:
    {{- include "keycloak-config-operator.labels" $ | nindent 4 }}
rules:
  {{- include "keycloak-config-operator.namespacedRules" $ | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "keycloak-config-operator.fullname" $ }}
  namespace: {{ $namespace | quote }}
  labels:
    {{- include "keycloak-config-operator.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "keycloak-config-operator.fullname" $ }}
subjects:
  - kind: ServiceAccount
    name: {{ include "keycloak-config-operator.serviceAccountName" $ }}
    namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
