apiVersion: keycloak.clouddicted.com/v1beta1
kind: KeycloakTarget
metadata:
  name: example-keycloak
spec:
  url: http://keycloak.keycloak.svc.cluster.local:8080
  auth:
    type: ClientCredentials
    realm: master
    clientCredentials:
      clientId: keycloak-config-operator
      secretRef:
        name: keycloak-operator-client
        clientSecretKey: clientSecret
