apiVersion: keycloak.clouddicted.com/v1beta1
kind: KeycloakRole
metadata:
  name: example-admin
spec:
  targetRef:
    name: example-keycloak
  realm: example
  name: example-admin
  description: Example administrator role
