apiVersion: keycloak.clouddicted.com/v1alpha1
kind: KeycloakTarget
metadata:
  name: example-keycloak
spec:
  url: https://keycloak.example.com
  adminCredentials:
    secretRef:
      name: keycloak-admin-credentials
      usernameKey: username
      passwordKey: password
