"""Shared operator constants."""

OPERATOR_NAME = "clouddicted-keycloak-config-operator"
API_GROUP = "keycloak.clouddicted.com"
API_VERSION = "v1beta1"
KEYCLOAK_CLIENT_SCOPE_PLURAL = "keycloakclientscopes"
KEYCLOAK_CLIENT_ROLE_PLURAL = "keycloakclientroles"
KEYCLOAK_CLIENT_PLURAL = "keycloakclients"
KEYCLOAK_GROUP_PLURAL = "keycloakgroups"
KEYCLOAK_GROUP_ROLE_MAPPING_PLURAL = "keycloakgrouprolemappings"
KEYCLOAK_IDENTITY_PROVIDER_PLURAL = "keycloakidentityproviders"
KEYCLOAK_PROTOCOL_MAPPER_PLURAL = "keycloakprotocolmappers"
KEYCLOAK_REALM_PLURAL = "keycloakrealms"
KEYCLOAK_ROLE_PLURAL = "keycloakroles"
KEYCLOAK_TARGET_PLURAL = "keycloaktargets"

KEYCLOAK_RESOURCE_PLURALS = (
    KEYCLOAK_TARGET_PLURAL,
    KEYCLOAK_REALM_PLURAL,
    KEYCLOAK_CLIENT_PLURAL,
    KEYCLOAK_CLIENT_ROLE_PLURAL,
    KEYCLOAK_GROUP_PLURAL,
    KEYCLOAK_GROUP_ROLE_MAPPING_PLURAL,
    KEYCLOAK_IDENTITY_PROVIDER_PLURAL,
    KEYCLOAK_ROLE_PLURAL,
    KEYCLOAK_CLIENT_SCOPE_PLURAL,
    KEYCLOAK_PROTOCOL_MAPPER_PLURAL,
)
