"""Shared operator constants."""

OPERATOR_NAME = "clouddicted-keycloak-config-operator"
API_GROUP = "keycloak.clouddicted.com"
API_VERSION = "v1beta1"
KEYCLOAK_CLIENT_SCOPE_PLURAL = "keycloakclientscopes"
KEYCLOAK_CLIENT_PLURAL = "keycloakclients"
KEYCLOAK_IDENTITY_PROVIDER_PLURAL = "keycloakidentityproviders"
KEYCLOAK_PROTOCOL_MAPPER_PLURAL = "keycloakprotocolmappers"
KEYCLOAK_REALM_PLURAL = "keycloakrealms"
KEYCLOAK_ROLE_PLURAL = "keycloakroles"
KEYCLOAK_TARGET_PLURAL = "keycloaktargets"
