apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - keycloak.clouddicted.com_keycloaktargets.yaml
  - keycloak.clouddicted.com_keycloakrealms.yaml
  - keycloak.clouddicted.com_keycloakclients.yaml
  - keycloak.clouddicted.com_keycloakroles.yaml
  - keycloak.clouddicted.com_keycloakclientscopes.yaml
  - keycloak.clouddicted.com_keycloakprotocolmappers.yaml
